spring:
  datasource:
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8888/cache

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
#    root: debug


